### ISSUE TITLE
Copy functionality causes build failure on iOS

### ISSUE THREAD

**Issue by adrianz** [varkrishna/JSONViewer#1]
Because of the `NSPasteboard` usage the package cannot be used in the iOS environment. [This section](https://github.com/varkrishna/JSONViewer/compare/v3.0.3...v3.04#diff-aa60356f53b52e179bf18b581e697c2f4e2d1b66da83afb9cf461c0e83e01caeR59-R70) (roughly) should be in the `#if os(macOS)` block or something like that.

**Comment by varkrishna** [comment]
Fix is done in v3.05
